### ISSUE TITLE
Summary of discussion on machine

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#230] opened 2017-06-19 20:42 UTC
After @favonia's productive chat with Bob, @favonia and I have discussed the status of the machine, and it seems largely correct except for one very bad bug which we need to fix. In the course of fixing it, we hope that we can achieve a more efficient and well-structured machine simultaneously.

The issue is that the machine seems to be correct for code which does not compute under dimension binders, but it is definitely not correct for computation which does go underneath a binder. The problem is in the `unload` phase, which is invoked when a **neutral** term is in focus: the focused term gets plugged into the nearest stack frame, and the environment of the focused term gets wrapped around the resulting term, which becomes the focus. This is correct behavior for computation that does not go underneath a binder, but it is not correct when we are underneath a binder: since by plugging the term into the binder, we lose the identity of a variable in the context, since the variable becomes bound.

***Note***: The `unload` phase *only* can occur when we are computing with open terms. With closed terms, it cannot occur. The `up` phase (which is the ordinary way in which a *value* is pushed up the stack) seems to have no such flaw.

The way to fix this is to use a *second-order* environment, so that we can perform a substitution which can see the bound variable. In older literature, it is common to see this as a kind of "capture-inducing substitution", but as far as we are concerned, bound variables don't have names, so it makes more sense to think of it as the substitution of a binder for a second-order variable. (I believe that this perspective comes from either Hamana or Fiore, though I can't remember.)

/cc @RobertHarper @cangiuli

**Comment by RobertHarper** [comment] 2017-06-19 20:49
cool!

bob

(c) Robert Harper  All Rights Reserved.

**Comment by favonia** [comment] 2017-06-19 22:03
Related issues: #221, https://github.com/RedPRL/sml-typed-abts/issues/86. I guess we can close all of these once the more powerful environments are implemented.

**Comment by jonsterling** [comment] 2017-06-29 15:37
@favonia Please don't feel obligated to respond to this soon, since I know you're quite busy at Big Proof! Let me just write down something I was thinking...

I was thinking a bit more about the case of evaluating under a dimension binder (e.g. the commutative case for `coe`). Even given the current weird behavior of `unload`, in which the closure's environment gets re-wrapped around the innermost stack frame, I don't think that this can lead to incorrect behavior.

Consider that we are evaluating `(coe_{x.A[x]}(M), E) <: K`; the next step is approximately to evaluate `(A[x], E) <: (coe_{x.—}(M); K)`. Now, at this point, it is an invariant of the current operational semantics (I believe) that a substitution for `x` will never get added to the environment `E` in the course of evaluating `A[x]`; when `A[x]` turns out to be neutral, we will begin unloading—at which point, `x` will lose its identity because it becomes bound. Now, the thing that I thought we were worried about was that `x` would be in the environment, and so we would lose whatever substitution we had in mind as the "free" `x` becomes distinct from the bound `x`. I don't think this can happen.


Maybe I have become confused, but it seems to me that the main problem here is that the design is not very good—but I can't figure out a counterexample which would demonstrate that it is unsound. I also can't remember why we thought we needed to use second-order substitutions in the environment.

Were we worried about another case or possible problem?

**Comment by jonsterling** [comment] 2017-06-29 18:19
I began to write down some very rough thoughts on the machine here: https://github.com/RedPRL/sml-redprl/blob/master/doc/machine.pdf

We can use that document to brainstorm what the best approach is.

**Comment by favonia** [comment] 2017-06-29 19:53
@jonsterling I forgot what I was worried about, but one problem is that the returned environment might refer to `x`. An easy solution is to use forcing, but I want to avoid that, and so I am considering meta variables.

**Comment by jonsterling** [comment] 2017-06-29 19:55
@favonia That makes sense, but I think it is an invariant of our operational semantics that `x` will not be referred to in the returned environment. Anyway, I think it makes sense to figure out how to do this properly, but I am thinking currently that if we redesign the system, we will not need metavariables / second order variables at all for this part.

Anyway, we can chat about it when you get back.

**Comment by favonia** [comment] 2017-06-29 19:57
I think an example would be `u.(\lam y.....)(...something with u...)` and you could end up with an environment with `y` pointing to some expression containing `u`.

**Comment by favonia** [comment] 2017-06-29 20:02
Oh I should clarify that I mean it's probably true that the environment will not have a substitution for `u`, but other parts in the environment could potentially mention `u`.

**Comment by jonsterling** [comment] 2017-06-29 20:17
@favonia Ah, that makes sense, thanks!

I think that if we design the structure of the machine properly, we will completely avoid this issue however... But we'll find out i guess 😄 

I've proposed a tentative structure for the machine in the pdf I linked (https://github.com/RedPRL/sml-redprl/blob/master/doc/machine.pdf), which doesn't use second-order variables, and which I *think* is not susceptible to the problem that you observed (but I'm not sure). The main issue with the design that I proposed is that you still have to force substitutions in the dynamics for `coe` at non-base-types... But without explicit substitutions (which are gnarly), I think that is impossible to fix. But maybe we can find a better way.

**Comment by favonia** [comment] 2017-06-29 20:35
@jonsterling I believe your proposal is safe, but then I want to avoid forcing (without explicit substitution). I think it is possible to fix it with second-order variables. For example the product type can probably:
```
(A * B <: E) || (coe({ }, M), E', [x]) >- <coe_x.{\alpha[x]}(fst(M)), coe_x.{\beta[x]}(snd(M)) <: [E',alpha->(x.A<:E),beta>->(x.B<:[E,...])] >
```

**Comment by jonsterling** [comment] 2017-06-29 22:19
@favonia Aha, this is an example that helps me understand why you want the second order variables! Thanks very much. I'll start thinking about it!!

**Comment by jonsterling** [comment] 2017-06-29 22:20
@favonia Wow, that's a really brilliant Thought, I think I see what you were talking about now. Thanks!

**Comment by favonia** [comment] 2017-06-30 01:45
@jonsterling I took a look and your typesetting is amazing! Anyways, two ideas about the unloading:

1. the second rule can be made without forcing, in the same way, and
2. with the meta variables the first rule could potentially be very inefficient, and maybe we can use the algorithm I sketched out in another email.

The issue is that when forcing `alpha[r,M] :> [alpha -> x.a.<N,E>, ...]` you do not want to force alpha, force the parameters, and then compute the final results. This naive approach walks through <N,E> twice. Another naive approach is to force the parameters, force the environment of E with the substitution [x -> ..., a -> ...] and then force N with the new environment. Walking through the entire environment sounds just bad to me. A better solution in my opinion is the two-layer forcing I sketched out in the email. Not sure if this already showed up somewhere in the literature.

**Comment by jonsterling** [comment] 2017-06-30 02:14
I will study your note on unloading; I had trouble understanding how it worked, but I can take another look :) I have a feeling the naïve version I wrote down would be horribly inefficient.

**Comment by favonia** [comment] 2017-07-01 06:42
@jonsterling Ah, I just realized we might run into the same problem when evaluating the meta variables! In the current PDF, what if some parts of `E'` use `x` or `a`? I will check whether I can merge the idea of 2-layer forcing into dynamics to fix this. Currently it's potentially buggy.

**Comment by favonia** [comment] 2017-07-01 10:27
On the other hand, if this is the only place forcing is needed, I think I am fine with it.

**Comment by favonia** [comment] 2017-07-22 12:03
Close this because we are using eager substitution without closures now. #262

**Closed by favonia** 2017-07-22 12:03 UTC
Labels: A-computation-system
